const hearts = ['https://upload.wikimedia.org/wikipedia/commons/0/07/Ace_of_hearts.svg', 'https://upload.wikimedia.org/wikipedia/commons/d/d5/Playing_card_heart_2.svg','https://upload.wikimedia.org/wikipedia/commons/b/b6/Playing_card_heart_3.svg','https://upload.wikimedia.org/wikipedia/commons/a/a2/Playing_card_heart_4.svg','https://upload.wikimedia.org/wikipedia/commons/5/52/Playing_card_heart_5.svg','https://upload.wikimedia.org/wikipedia/commons/c/cd/Playing_card_heart_6.svg','https://upload.wikimedia.org/wikipedia/commons/4/4a/7_of_hearts.svg','https://upload.wikimedia.org/wikipedia/commons/6/6b/8_of_hearts.svg','https://upload.wikimedia.org/wikipedia/commons/9/9d/9_of_hearts.svg','https://upload.wikimedia.org/wikipedia/commons/9/98/Playing_card_heart_10.svg','https://upload.wikimedia.org/wikipedia/commons/5/56/English_pattern_jack_of_hearts.svg','https://upload.wikimedia.org/wikipedia/commons/9/9d/English_pattern_queen_of_hearts.svg','https://upload.wikimedia.org/wikipedia/commons/f/fa/King_of_hearts_fr.svg'];
const diamonds = ['https://upload.wikimedia.org/wikipedia/commons/d/d3/Playing_card_diamond_A.svg','https://upload.wikimedia.org/wikipedia/commons/5/59/Playing_card_diamond_2.svg','https://upload.wikimedia.org/wikipedia/commons/0/00/03_of_diamonds.svg','https://upload.wikimedia.org/wikipedia/commons/8/80/04_of_diamonds.svg','https://upload.wikimedia.org/wikipedia/commons/2/2e/05_of_diamonds.svg','https://upload.wikimedia.org/wikipedia/commons/3/34/6_of_diamonds.svg','https://upload.wikimedia.org/wikipedia/commons/8/83/7_of_diamonds.svg','https://upload.wikimedia.org/wikipedia/commons/4/42/08_of_diamonds.svg','https://upload.wikimedia.org/wikipedia/commons/2/2c/09_of_diamonds.svg','https://upload.wikimedia.org/wikipedia/commons/3/34/Playing_card_diamond_10.svg','https://upload.wikimedia.org/wikipedia/commons/1/16/English_pattern_jack_of_diamonds.svg','https://upload.wikimedia.org/wikipedia/commons/0/00/Queen_of_diamonds_fr.svg','https://upload.wikimedia.org/wikipedia/commons/6/66/King_of_diamonds_en.svg'];
const clubs = ['https://upload.wikimedia.org/wikipedia/commons/6/61/Ace_of_clubs.svg','https://upload.wikimedia.org/wikipedia/commons/f/f5/Playing_card_club_2.svg','https://upload.wikimedia.org/wikipedia/commons/f/f9/03_of_clubs.svg','https://upload.wikimedia.org/wikipedia/commons/a/ab/04_of_clubs.svg','https://upload.wikimedia.org/wikipedia/commons/5/50/Playing_card_club_5.svg','https://upload.wikimedia.org/wikipedia/commons/b/be/06_of_clubs.svg','https://upload.wikimedia.org/wikipedia/commons/4/4b/Playing_card_club_7.svg','https://upload.wikimedia.org/wikipedia/commons/e/eb/Playing_card_club_8.svg','https://upload.wikimedia.org/wikipedia/commons/2/27/Playing_card_club_9.svg','https://upload.wikimedia.org/wikipedia/commons/b/bb/10_of_clubs_-_David_Bellot.svg','https://upload.wikimedia.org/wikipedia/commons/d/df/Jack_of_clubs_fr.svg','https://upload.wikimedia.org/wikipedia/commons/b/b3/English_pattern_queen_of_clubs.svg','https://upload.wikimedia.org/wikipedia/commons/0/04/King_of_clubs_en.svg'];
const spades = ['https://upload.wikimedia.org/wikipedia/commons/a/ab/01_of_spades_A.svg','https://upload.wikimedia.org/wikipedia/commons/f/f2/Playing_card_spade_2.svg,','https://upload.wikimedia.org/wikipedia/commons/5/52/Playing_card_spade_3.svg','https://upload.wikimedia.org/wikipedia/commons/2/2c/Playing_card_spade_4.svg','https://upload.wikimedia.org/wikipedia/commons/9/94/Playing_card_spade_5.svg','https://upload.wikimedia.org/wikipedia/commons/d/d2/Playing_card_spade_6.svg','https://upload.wikimedia.org/wikipedia/commons/6/66/Playing_card_spade_7.svg','https://upload.wikimedia.org/wikipedia/commons/2/21/Playing_card_spade_8.svg','https://upload.wikimedia.org/wikipedia/commons/4/4f/09_of_spades.svg','https://upload.wikimedia.org/wikipedia/commons/8/87/Playing_card_spade_10.svg','https://upload.wikimedia.org/wikipedia/commons/4/4f/English_pattern_jack_of_spades.svg','https://upload.wikimedia.org/wikipedia/commons/c/ca/English_pattern_queen_of_spades.svg','https://upload.wikimedia.org/wikipedia/commons/f/f1/English_pattern_king_of_spades.svg'];

function getCard(suit, value) {
    if (suit === 'hearts') {
        return hearts[value - 1];
    } else if (suit === 'diamonds') {
        return diamonds[value - 1];
    } else if (suit === 'clubs') {
        return clubs[value - 1];
    } else if (suit === 'spades') {
        return spades[value - 1];
    }
}

module.exports = getCard;